config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'

  get 'about', to: 'about#index', as: :about

  get 'detail', to: 'detail#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/detail_controller.rb
class DetailController < ApplicationController
  def index
    
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  BASE_URL = "https://api.stagingeb.com/v1"

  def index
    response = RestClient.get(
      "https://api.stagingeb.com/v1/properties",
      headers={ "X-Authorization" => "l7u502p8v46ba3ppgvj5y2aad50lb9" }
    )
    parsed_response = JSON.parse response

    @properties = parsed_response["content"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>Acerca de</h1>

<p>
EasyBroker comenzó en 2007 y ahora somos más de 20 personas en el equipo con más de 3,000 clientes en 15 países latinoamericanos. Nuestra sede está en la Ciudad de México y nuestro equipo es libre de trabajar desde casa o desde cualquier lugar que prefieran. Somos un equipo muy diverso que viene de varias disciplinas pero todos enfocados en crear productos digitales que nuestros clientes amen.
</p>

<p>
Nuestra meta es mejorar la experiencia de encontrar un hogar ayudando a profesionales inmobiliarios a proveer el mejor servicio. EasyBroker es una plataforma en la nube que ayuda a los agentes a estar al tanto de sus tareas diarias y a colaborar fácilmente con sus clientes y otros colegas inmobiliarios.
</p>

app/views/detail/index.html.erb
<h2>Property detail</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyBrokerProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %1> %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1 class="text-center">Welcome to Real State</h1>

<div class="d-flex flex-wrap justify-content-between">
<% @properties.each do |property| %>
  <div class="card" style="width: 18rem;">
    <img src="<%= property["title_image_thumb"] %>" class="card-img-top" alt="Property image">
    <div class="card-body">
      <h5 class="card-title"><%= property["title"] %></h5>
      <p class="card-text">Tipo: <%= property["property_type"] %></p>
      <p class="card-text">Ubicación: <%= property["location"] %></p>
      <h6 class="card-title">ID: <%= property["public_id"] %></h6>
      <%# <a href="" class="btn btn-primary">Ver detalle</a> %>
      <%= link_to "Ver detalle", detail_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "EasyBroker", root_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Acerca de", about_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>